posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_list_view, name='main_post_view'),
    path('like_unlike/',like_unlike,name='like_unlike'),
    path('<pk>/delete/',post_delete_view.as_view(),name='post_delete_view'),
    path('<pk>/update/',post_update_view.as_view(),name='post_update_view'),
]

profiles/urls.py
from django.urls import path
from .views import *

app_name = 'profiles'
urlpatterns = [
    path('myprofile', my_profile, name='myprofile'),
    path('profile_detail/<slug>/',profiles_detail_view.as_view(),name='profile_detail'),
    path('my_invites/',invite_recieved_view,name='my_invites'),
    path('all_profiles/',all_profiles,name='all_profiles'),
    path('profiles_available_for_inviting/',profiles_available_for_inviting.as_view(),name='profiles_available_for_inviting'),
    path('send_invitation/',send_invitation,name='send_invitation'),
    path('remove_friend/',remove_from_friends,name='remove_friend'),
    path('my_invites/accept/',accept_invitation,name='accept_invitation'),
    path('my_invites/reject/',reject_invitation,name='reject_invitation'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name='home'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('profiles/',include('profiles.urls',namespace='profiles')),
    path('accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import get_random_code
from django.template.defaultfilters import slugify
from django.db.models import Q
from django.shortcuts import reverse


# from posts.models import *

class ProfileManager(models.Manager):
    def get_all_profiles_to_invites(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(reciever=profile))
        accepted = set([])
        for rel in qs:
            if rel.status == 'accepted':
                accepted.add(rel.reciever)
                accepted.add(rel.sender)
        avilable = [profile for profile in profiles if profile not in accepted]
        return avilable

    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles


class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True, null=True)
    last_name = models.CharField(max_length=200, blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=300, default="no bio.......")
    email = models.EmailField(max_length=200, blank=True, null=True)
    country = models.CharField(max_length=200, blank=True, null=True)
    avatar = models.ImageField(default='avatar.jpg', upload_to='avatars/')
    friends = models.ManyToManyField(User, blank=True, related_name='friends')
    slug = models.SlugField(unique=True, blank=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    objects = ProfileManager()

    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%d-%m-%y')}"

    def get_absolute_url(self):
        return reverse('profiles:profile_detail', kwargs={'slug': self.slug})


    def get_friends(self):
        return self.friends.all()


    def get_friends_no(self):
        return self.friends.all().count()


    def get_likes_no(self):
        return self.post_likes.all().count()


    def get_posts_no(self):
        return self.Post_set.all().count()


    def get_all_authors_posts(self):
        return self.Post_set.all()

    # def get_likes_given_no(self):
    #     likes = self.likee.all()
    #     total_liked = 0
    #     for item in likes:
    #         if item.value == 'like':
    #             total_liked += 1
    #     return total_liked


    def get_likes_given_no(self):
        total_liked = self.likee.filter(value='like').count()
        return total_liked


    def get_liked_recieved_no(self):
        posts = self.Post_set.all()
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()
        return total_liked


__initial_first_name = None
__initial_last_name = None


def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.__initial_first_name = self.first_name
    self.__initial_last_name = self.last_name


def save(self, *args, **kwargs):
    ex = False
    to_slug = self.slug
    if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or not self.slug:
        if self.first_name and self.last_name:
            to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
            ex = Profile.objects.filter(slug=to_slug).exists()
            while ex:
                to_slug = slugify(to_slug + " " + str(get_random_code()))
                ex = Profile.objects.filter(slug=to_slug).exists()
        else:
            to_slug = str(self.user)
    self.slug = to_slug
    super().save(*args, **kwargs)


STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)


class RelationshipManager(models.Manager):
    def invitation_recieved(self, reciever):
        qs = Relationship.objects.filter(reciever=reciever, status='send')
        return qs


class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    reciever = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='reciever')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender}-{self.reciever}-{self.status}"

profiles/forms.py
from django import forms
from .models import *


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'bio', 'avatar']

profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .models import *
from .forms import ProfileModelForm
from django.views.generic import ListView,DetailView
from django.db.models import Q


def my_profile(request):
    obj = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=obj)
    confirm = False
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True
    context = {
        'obj': obj,
        'form': form,
        'confirm': confirm,
    }
    return render(request, 'profiles/myprofile.html', context)


def invite_recieved_view(request):
    profile = Profile.objects.get(user=request.user)
    qs = Relationship.objects.invitation_recieved(profile)
    results = list(map(lambda x: x.sender, qs))
    is_empty = False
    if len(results) == 0:
        is_empty = True
    return render(request, 'profiles/my_invites.html', {'qs': results, 'is_empty': is_empty})


def accept_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        reciever = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, reciever=reciever)
        if rel.status == 'send':
            rel.status = 'accepted'
            rel.save()
    return redirect('profiles:my_invites')


def reject_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        reciever = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, reciever=reciever)
        rel.delete()
    return redirect('profiles:my_invites')


def all_profiles(request):
    user = request.user
    qs = Profile.objects.get_all_profiles(user)
    return render(request, 'profiles/all_profiles.html', {'qs': qs})


# def profiles_available_for_inviting(request):
#     user = request.user
#     qs = Profile.objects.get_all_profiles_to_invites(user)
#     return render(request, 'profiles/profiles_avilable_for_inviting.html', {'qs': qs})

class profiles_detail_view(DetailView):
    model=Profile
    template_name = 'profiles/details.html'

    def get_object(self,slug=None):
        slug=self.kwargs.get('slug')
        profile=Profile.objects.get(slug=slug)
        return profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(reciever=profile)
        rel_sender = []
        rel_reciever = []
        for item in rel_r:
            rel_reciever.append(item.reciever.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context['rel_reciever'] = rel_reciever
        print(rel_reciever)
        context['rel_sender'] = rel_sender
        context['posts']=self.get_object().get_all_authors_posts()
        print(self.get_object().get_all_authors_posts())
        context['len_posts']=True if len(self.get_object().get_all_authors_posts())>0 else False


        return context


class profiles_available_for_inviting(ListView):
    model = Profile
    template_name = 'profiles/profiles_avilable_for_inviting.html'
    context_object_name = 'qs'

    def get_queryset(self):
        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(reciever=profile)
        rel_sender = []
        rel_reciever = []
        for item in rel_r:
            rel_reciever.append(item.reciever.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context['rel_reciever'] = rel_reciever
        print(rel_reciever)
        context['rel_sender'] = rel_sender
        context['is_empty'] = False
        if len(self.get_queryset()) == 0:
            context['is_empty'] = True
        return context


def send_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        reciever = Profile.objects.get(pk=pk)
        sender = Profile.objects.get(user=request.user)
        rel = Relationship.objects.create(sender=sender, reciever=reciever, status='send')
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profile:myprofile')


def remove_from_friends(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        reciever = Profile.objects.get(pk=pk)
        sender = Profile.objects.get(user=request.user)
        rel = Relationship.objects.filter(
            (Q(sender=sender) & Q(reciever=reciever)) | (Q(sender=reciever) & Q(reciever=sender))
        )
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profile:myprofile')

profiles/templates/profiles/all_profiles.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
all profiles
<ul>
    {% for item in qs %}
    <li>{{ item }}</li>
    {% endfor %}
</ul>
{% endblock content %}

profiles/templates/profiles/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>the profile detail</h1>
<div class="ui grid">
    <div class="row">
        <div class="four wide column">
            <img class="ui medium rounded image" src="{{ object.avatar.url }}" alt="">
            <h1>{{object.user}}</h1>
            <div class="ui vertical fluid menu">
                <div class="item">posts
                    <div class="ui label">
                        {{object.get_posts_no}}
                    </div>
                </div>
                <div class="item">likes given
                    <div class="ui label">
                        {{object.get_likes_given_no}}
                    </div>
                </div>
                <div class="item">likes received
                    <div class="ui label">
                        {{object.get_liked_recieved_no}}
                    </div>

                </div>
                <div class="item">friends no
                    <div class="ui label">
                        {{object.get_friends_no}}
                    </div>
                </div>
            </div>
            {% if object.user not in rel_reciever and object.user not in rel_sender %}
            <form action="{% url 'profiles:send_invitation' %}" method="post">{%csrf_token%}
                <input type="hidden" name="profile_pk" value="{{object.pk}}">
                <button class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i> add to friends
                </button>
            </form>
            {% endif %}
            <br>
            {% if object.user in rel_reciever and request.user not in object.friends.all %}
            <button class="ui disabled   button mb-5 w-big"><i class="user icon"></i>waiting for approve</button>
            {% endif %}
            {% if request.user in object.friends.all %}

            <form action="{% url 'profiles:remove_friend' %}" method="post">{%csrf_token%}
                <input type="hidden" name="profile_pk" value="{{object.pk}}">
                <button class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>remove from friends
                    list
                </button>
            </form>
            {% endif %}


        </div>


        <div class="twelve wide column">
            {% if len_posts %}
            {% for post in posts %}
            <div class="ui segment fluid">
                {{ post.content }}
            </div>

            {% endfor %}
            {% else %}
            there is no posts to show righ now
            {% endif %}
        </div>

    </div>
    {% endblock content %}

profiles/templates/profiles/my_invites.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
my invites

{% if is_empty %}
<h3>no invites to show</h3>
{% endif %}
{% for obj in qs %}
<div class="ui segment">
    <div class="ui grid">
        <div class="row">
            <div class="three wide column">
                <img class="ui circular small image" src="{{obj.avatar.url}}">
            </div>
            <div class="thirteen wide column">
                <h3>{{obj.user}}</h3>
                <p>{{obj.bio}}</p>
                <a href="">
                    <button class="ui primary button w-big mb-5">see profile</button>
                </a>
                <form action="{% url 'profiles:accept_invitation' %}" method="post">{%csrf_token%}
                    <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                    <button type="submit" class="ui positive basic button w-big mb-5">
                        <i class="check icon"></i>accept</button>
                </form>
                <form action="{% url 'profiles:reject_invitation' %}" method="post">{%csrf_token%}
                    <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                    <button type="submit" class="ui negative basic button w-big mb-5">
                        <i class="close icon"></i>reject</button>
                </form>

            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock content %}

profiles/templates/profiles/myprofile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--start=modal-->
<div class="ui modal mymodal">
    <i class="close icon"></i>
    <div class="header">
        update profile
    </div>
    <div class="image content">
        <div class="ui medium image">
            <img src="{{ obj.avatar.url }}">
        </div>
        <div class="description">
            <div class="ui header">provide new info in your profile</div>
            <form method="post" action="" class="ui form" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}

        </div>
    </div>
    <div class="actions">
        <div class="ui black deny button">
            Nope
        </div>
        <button type="submit" class="ui positive right labeled icon button">
            update
            <i class="checkmark icon"></i>
        </button>
        </form>
    </div>
</div>
<!--end-modal-->
<div class="ui segment">
    {% if confirm == True %}
    <div class="ui green message">your profile updated successfully</div>
    {% endif %}
    <h3>my profile:{{ request.user}}</h3>
    <div class="ui grid">
        <div class="row">
            <div class="six wide column">
                <img class="ui medium rounded image" src="{{ obj.avatar.url }}">
                <div class="row mt-5">
                    <button class="ui secondary button" id="modal_btn">update</button>
                </div>
            </div>
            <div class="ten wide column">
                <table calss="ui table">
                    <tbody>
                    <tr>
                        <td>user name</td>
                        <td>{{ obj.user.username }}</td>
                    </tr>
                    <tr>
                        <td>first name</td>
                        <td>{{ obj.first_name }}</td>
                    </tr>
                    <tr>
                        <td>last name</td>
                        <td>{{ obj.last_name }}</td>
                    </tr>
                    <tr>
                        <td>bio</td>
                        <td>{{ obj.bio }}</td>
                    </tr>
                    <tr>
                        <td>no of friends</td>
                        <td>{{ obj.get_friends_no }}</td>
                    </tr>
                    <tr>
                        <td> friends</td>

                        <td>
                            <ul>
                                {% for friend in obj.get_friends %}
                                    <li>{{ friend }}</li>
                                {% endfor %}
                            </ul>

                        </td>
                    </tr>
                    <tr>
                        <td>no of posts</td>
                        <td>{{ obj.get_posts_no }}</td>
                    </tr>
                    <tr>
                        <td>no of likes given</td>
                        <td>{{ obj.get_likes_given_no }}</td>
                    </tr>
                    <tr>
                        <td>no of likes recieved</td>
                        <td>{{ obj.get_liked_recieved_no }}</td>
                    </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

profiles/templates/profiles/profiles_avilable_for_inviting.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
all profiles
{% endblock title %}
{% block content %}

{% if is_empty %}
no profiles to show in the mean time
{% endif %}
{% for object in object_list %}
<div class="ui segment">
    <div class="ui grid">
        <div class="row">
            <div class="three wide columns">
                <img class="ui small circular image" src="{{object.avatar.url}}" alt="img">
            </div>
            <div class="thirteen wide columns">
                <h3>{{object.user}}</h3>
                <p>{{object.bio}}</p>
                <a href="{{object.get_absolute_url}}">
                    <button class="ui primary button mb-5 w-big">see profile</button>
                </a>
                {% if object.user not in rel_reciever and object.user not in rel_sender %}
                <form action="{% url 'profiles:send_invitation' %}" method="post">{%csrf_token%}
                    <input type="hidden" name="profile_pk" value="{{object.pk}}">
                    <button class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i> add to friends
                    </button>
                </form>
                {% endif %}
                <br>
                {% if object.user in rel_reciever and request.user not in object.friends.all %}
                <button class="ui disabled   button mb-5 w-big"><i class="user icon"></i>waiting for approve</button>
                {% endif %}
                {% if request.user in object.friends.all %}

                <form action="{% url 'profiles:remove_friend' %}" method="post">{%csrf_token%}
                    <input type="hidden" name="profile_pk" value="{{object.pk}}">
                    <button class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>remove from
                        friends list
                    </button>
                </form>
                {% endif %}

            </div>
        </div>
    </div>
</div>
{% endfor%}


{% endblock content %}