posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_list_view, name='main_post_view'),
    path('like_unlike/',like_unlike,name='like_unlike'),
    path('<pk>/delete/',post_delete_view.as_view(),name='post_delete_view'),
    path('<pk>/update/',post_update_view.as_view(),name='post_update_view'),
]

profiles/urls.py
from django.urls import path
from .views import *

app_name = 'profiles'
urlpatterns = [
    path('myprofile', my_profile, name='myprofile'),
    path('profile_detail/<slug>/',profiles_detail_view.as_view(),name='profile_detail'),
    path('my_invites/',invite_recieved_view,name='my_invites'),
    path('all_profiles/',all_profiles,name='all_profiles'),
    path('profiles_available_for_inviting/',profiles_available_for_inviting.as_view(),name='profiles_available_for_inviting'),
    path('send_invitation/',send_invitation,name='send_invitation'),
    path('remove_friend/',remove_from_friends,name='remove_friend'),
    path('my_invites/accept/',accept_invitation,name='accept_invitation'),
    path('my_invites/reject/',reject_invitation,name='reject_invitation'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name='home'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('profiles/',include('profiles.urls',namespace='profiles')),
    path('accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/main/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


{% endblock content %}

templates/main/navbar.html
{% url 'home' as path_to_home %}
{%  url 'posts:main_post_view' as path_to_posts %}
{% url 'profiles:myprofile' as path_to_my_profile %}
{% url 'profiles:my_invites' as path_to_my_invites %}
{% url 'profiles:all_profiles' as path_to_all_profiles %}
{% url 'profiles:profiles_available_for_inviting' as path_to_available_for_invite %}




<div class="ui inverted menu nav mb-7">
  <div class="ui container">
    <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item">
        <h3>bffbook</h3>
    </a>
    {% if request.user.is_authenticated %}
    <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item">
        board
    </a>
    {% endif %}

    <div class="right menu">
        {% if request.user.is_authenticated %}
        <div class="item">
            <div class="ui floating dropdown icon button teal"> Friends
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="{{ path_to_all_profiles }}" class="{% if request.path == path_to_all_profiles %} active {% endif %} item">
                        All Profiles
                    </a>
                    <a href="{{ path_to_available_for_invite }}" class="{% if request.path == path_to_available_for_invite %} active {%endif%} item">
                        Send Invites
                    </a>
                    <a href="{{ path_to_my_invites }}" class="{% if request.path == path_to_my_invites %} active {%endif%} item">
                        Received Invites &nbsp; <div class="ui purple horizontal label">{{invitations_no}}</div>
                    </a>
                </div>
             </div>
        </div>
             <div class="item">
              <form action="" method="GET">
                <div class="ui action left icon input">
                <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                <i class="search icon"></i>
                <button type='submit' class="ui button">Search</button>
                </div>
            </form>
            </div>

            <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %} active {% endif %}item">
                 <img class="ui avatar image" src="{{avatar_pic.url}}">
                 {{ request.user }}
            </a>

            <a href="{% url 'account_logout' %}" class="ui item">
                Logout
            </a>
        {% else %}
        <a href="{% url 'account_login' %}" class="ui item">
                Login
            </a>
        {% endif %}
    </div>
  </div>
</div>