posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_list_view, name='main_post_view'),
    path('like_unlike/',like_unlike,name='like_unlike'),
    path('<pk>/delete/',post_delete_view.as_view(),name='post_delete_view'),
    path('<pk>/update/',post_update_view.as_view(),name='post_update_view'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name='home'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('profiles/',include('profiles.urls',namespace='profiles')),
    path('accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import *


class Post(models.Model):
    content = models.TextField()
    image = models.ImageField(upload_to='posts/',
                              validators=[FileExtensionValidator(['jpg', 'jpeg', 'png'])], blank=True)
    liked = models.ManyToManyField(Profile, blank=True, related_name='post_likes')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='Post_set')

    def __str__(self):
        return str(self.content[:20])

    def num_likes(self):
        return self.liked.all().count()

    def num_comments(self):
        return self.Comments_set.all().count()

    class Meta:
        ordering = ('-created',)


class Comments(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='Comments_set')
    body = models.TextField(max_length=300)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)


LIKE_CHOICES = (
    ('like', 'like'),
    ('unlike', 'unlike'),
)


class Likes(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='likee')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(max_length=8, choices=LIKE_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(f"{self.user}-{self.post}-{self.value}")

posts/forms.py
from django import forms
from .models import *


class PostForm(forms.ModelForm):
    content=forms.CharField(widget=forms.Textarea(attrs={
        'rows':3,
    }))
    class Meta:
        model = Post
        fields = ['content','image']


class commentForm(forms.ModelForm):
    body=forms.CharField(label='',widget=forms.TextInput(attrs={
        'placeholder':'add a comment...',
    }))
    class Meta:
        model=Comments
        fields=['body']

posts/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import *
from django.views.generic import UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.models import User


@login_required(login_url='login/')
def post_comment_create_list_view(request):
    posts_form = PostForm()
    comment_form = commentForm()
    qs = Post.objects.all()
    profile = Profile.objects.get(user=request.user)
    if 'submit_comment_form' in request.POST:
        comment_form = commentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = profile
            comment.post = Post.objects.get(id=request.POST.get('post_id'))
            comment.save()
            comment_form = commentForm()
    if 'submit_posts_form' in request.POST:
        posts_form = PostForm(request.POST, request.FILES)
        if posts_form.is_valid():
            instance = posts_form.save(commit=False)
            instance.author = profile
            instance.save()
            posts_form = PostForm()
    context = {
        'qs': qs,
        'profile': profile,
        'posts_form': posts_form,
        'comment_form': comment_form,
    }
    return render(request, 'posts/main.html', context)


def like_unlike(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        the_post = Post.objects.get(id=post_id)
        if profile in the_post.liked.all():
            the_post.liked.remove(profile)
        else:
            the_post.liked.add(profile)
        like, created = Likes.objects.get_or_create(user=profile, post_id=post_id)
        if not created:
            if like.value == 'like':
                like.value = 'unlike'
            else:
                like.value = 'like'
        else:
            like.value = 'like'

        like.save()
        the_post.save()
        return redirect('/')


class post_delete_view(DeleteView):
    model = Post
    template_name = 'posts/confirm_delete.html'
    success_url = reverse_lazy('posts:main_post_view')

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = Post.objects.get(pk=pk)
        if not obj.author.user == self.request.user:
            messages.warning(self.request, 'you need to be the author of the post to delete it')
        return obj


class post_update_view(UpdateView):
    form_class = PostForm
    model = Post
    template_name = 'posts/update.html'
    success_url = reverse_lazy('posts:main_post_view')

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        if form.instance.author == profile:
            return super().form_valid(form)
        else:
            form.add_error(None, "you need to be the autor of the post to update it")
            return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super()

posts/templates/posts/confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>delete_post</h3>
{% if messages %}
{% for message in messages %}
{% if 'warning' in message.tags %}
<div class="ui negative message">
    <div class="header">
        {{ message }}
    </div>
</div>
{% endif %}
{% endfor %}
{% endif %}
{% if not messages %}
<div class=" ui segment">
    <h3>delete post?</h3>
    <form action="" method="post">
        {% csrf_token %}
        <p>are you sure you want to delete this post</p>
        {{ form }}
        <button type="submit" class="ui primary button">delete</button>
    </form>
</div>
{% endif %}
{% endblock content %}

posts/templates/posts/main.html
{% extends 'base.html' %}

{% block title %}main page{% endblock title %}

{% block content %}
<div class="ui grid">
    <div class="eleven wide column">
        {% for obj in qs %}

        <div class="ui fluid card">
            <div class="content">
                <div class="right floated meta">
                <div class="ui grid">
                    <div class="row">
                        {% ifequal request.user obj.author.user %}
                            <a href="{% url 'posts:post_update_view' obj.pk %}"><button class="ui button bwhite-lg ">Update</button></a>
                            <a href="{% url 'posts:post_delete_view' obj.pk %}"><button class="ui button bwhite-lg ">Delete</button></a>
                        {% endifequal %}
                    </div>
                </div>

                </div>
                <img class="ui avatar image" src={{obj.author.avatar.url}}>
                {{ obj.author.user }} - {{ obj.created|timesince}} ago
            </div>
            <div class="ui fluid image">
                {% if obj.image %}
                    <img src={{obj.image.url}}>
                {% endif %}
            </div>
            <div class="content">
                <p> {{ obj.content }} </p>
                <div class="right floated">
                    <form action="{% url 'posts:like_unlike' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value="{{obj.id}}">
                        {% if profile not in obj.liked.all %}
                            <button type="submit" class="ui bwhite-sm button"><i class="thumbs up icon"></i>
                            </button>
                            <span> {{obj.num_likes}} likes</span>
                        {% else %}
                            <button type="submit" class="ui bwhite-sm button"><i class="thumbs down icon"></i>
                            </button>
                            <span> {{obj.num_likes}} likes</span>
                        {% endif %}
                    </form>
                </div>
                <i class="comment icon"></i>
                <span> {{ obj.num_comments }} comments</span>
            </div>
            <div class="extra content">
                <div class="mb-5">

                </div>
                <button class="cmt_btn ui button mb-5">show / hide comments</button>
                <div class="comment-box">
                {% if obj.Comments_set.all %}
                    {% for c in obj.Comments_set.all %}

                        <div class="ui segment mb-5">
                            <img class="ui avatar image" src={{c.user.avatar.url}}>
                            <span>{{ c.user }}</span>
                            <div class='mt-5'>{{ c.body }}</div>
                        </div>

                    {% endfor %}
                {% endif %}
                </div>

                <form action="" method="POST"class='ui fluid form'>
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value={{obj.id}}>
                    {{ comment_form }}
                    <button type="submit" name="submit_comment_form" class="ui primary button mt-5 w-full">Send</button>
                </form>
            </div>
        </div>


        {% endfor %}
    </div>
    <div class="five wide column">
        <div class="ui segment">
            {% if post_added %}
                <div class="ui green message">Post added</div>
            {% endif %}
            <form action="" method="POST" class='ui form' enctype="multipart/form-data">
                {% csrf_token %}
                {{posts_form}}
                <button type='submit' name="submit_posts_form" class="ui positive button w-full mt-5">Send</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
    <script>
        $( document ).ready(function() {
            let display = false
            $(".cmt_btn").click(function () {
                if (display===false) {
                    $(this).next(".comment-box").show("slow");
                    display=true
                } else {
                    $(this).next(".comment-box").hide("slow");
                    display=false
                }
            });

        });




    </script>
{% endblock scripts %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block content %}
<div class="ui segment">
    <h3>update post</h3>
    <form action="" method="post" class="ui form" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="ui button primary mt-5">submit_update</button>
    </form>
</div>

{% endblock content %}